/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YPMmbW5UzzT
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useState } from "react";

export function CityNameForm({
  cityName,
  onChange,
  onSubmit,
}: {
  cityName: string;
  onChange: (cityName: string) => void;
  onSubmit: (cityName: string) => void;
}) {
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <div className="max-w-md w-full px-4 sm:px-6">
        <div className="space-y-4 text-center">
          <h1 className="text-4xl font-bold text-primary-foreground">City Sage</h1>
          <p className="text-lg text-primary-foreground/80">Discover a city your way</p>
          <form
            className="relative"
            onSubmit={(e) => {
              e.preventDefault();
              onSubmit(cityName);
            }}
          >
            <Input
              type="text"
              placeholder="Where are you going?"
              className="w-full rounded-full bg-primary/10 px-4 py-3 text-primary-foreground placeholder:text-primary-foreground/60 focus:outline-none focus:ring-primary"
              autoFocus
              value={cityName}
              onChange={(e) => onChange(e.target.value)}
            />
            <div className="mt-2">
              <Button
                type="submit"
                disabled={!cityName}
                className="w-full rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary"
              >
                Next
              </Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
