/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YPMmbW5UzzT
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { LandmarkIcon, LibraryIcon, TreesIcon, UtensilsIcon, BeerIcon, ArrowLeftIcon } from "lucide-react";

const predefinedInterests = [
  { label: "Landmarks", icon: <LandmarkIcon className="mr-2 h-4 w-4" /> },
  { label: "Museums", icon: <LibraryIcon className="mr-2 h-4 w-4" /> },
  { label: "Parks", icon: <TreesIcon className="mr-2 h-4 w-4" /> },
  { label: "Food", icon: <UtensilsIcon className="mr-2 h-4 w-4" /> },
  { label: "Pub Crawl", icon: <BeerIcon className="mr-2 h-4 w-4" /> },
];

export function InterestsForm({
  cityName,
  onBack,
  onSubmit,
}: {
  cityName: string;
  onBack: () => void;
  onSubmit: (interests: string) => void;
}) {
  const [interests, setInterests] = useState("");

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <div className="max-w-md w-full px-4 sm:px-6">
        <div className="space-y-4 text-center">
          <h1 className="text-4xl font-bold text-primary-foreground">
            <Button
              className="rounded-full bg-primary/10 p-2 h-auto mr-2 text-primary-foreground transition-colors hover:bg-primary/20 focus:outline-none focus:ring-2 focus:ring-primary align-middle"
              onClick={onBack}
            >
              <ArrowLeftIcon className="h-4 w-4" />
            </Button>
            City Sage
          </h1>
          <p className="text-lg text-primary-foreground/80">
            What do you want to see in{" "}
            <a
              className="text-primary-foreground italic capitalize underline underline-offset-4 decoration-2 hover:text-primary transition-all cursor-pointer white"
              onClick={onBack}
            >
              {" "}
              {cityName}{" "}
            </a>
            {" ?"}
          </p>
          <div className="flex flex-wrap justify-center gap-2">
            {predefinedInterests.map(({ label, icon }) => (
              <Button
                key={label}
                className="rounded-full bg-primary/10 px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/20 focus:outline-none focus:ring-2 focus:ring-primary border border-white-500/75"
                onClick={() => onSubmit(label)}
              >
                {icon}
                {label}
              </Button>
            ))}
          </div>
          <form
            className="relative"
            onSubmit={(e) => {
              e.preventDefault();
              onSubmit(interests);
            }}
          >
            <Input
              type="text"
              placeholder="What are your interests?"
              className="w-full rounded-full bg-primary/10 px-4 py-3 text-primary-foreground placeholder:text-primary-foreground/60 focus:outline-none focus:ring-primary"
              autoFocus
              value={interests}
              onChange={(e) => setInterests(e.target.value)}
            />
            <div className="mt-2">
              <Button
                type="submit"
                disabled={!interests}
                className="w-full rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary"
              >
                See your Walking Tour
              </Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
